version: '3.9'

services:
  be_184390_mysql:
    image: ghcr.io/business-zone/dresser-shop/be_184390_database:latest
    environment:
      MYSQL_DATABASE: prestashop
      MYSQL_ROOT_PASSWORD: root
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s

  be_184390_prestashop:
    image: ghcr.io/business-zone/dresser-shop/be_184390_prestashop:latest
    environment:
      PS_INSTALL_AUTO: 0
      PS_ERASE_DB: 0
      PS_DEV_MODE: 0
      DB_SERVER: mysql
      DB_USER: root
      DB_PASSWD: root
      DB_NAME: prestashop
      PS_DOMAIN: localhost:18440
      ADMIN_MAIL: prestadev@prestashop.com
      ADMIN_PASSWD: prestashop_dev
      PS_ENABLE_SSL: 1
      ALLOW_OVERRIDE: 1
      PS_LANGUAGE: pl
      PS_COUNTRY: PL
      SHOP_HTTPS_PORT: "18440"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s
    ports:
      - 18439:80
      - 18440:443