version: '3.9'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: prestashop
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./dbdump:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  prestashop:
    image: prestashop/prestashop:1.7
    environment:
      PS_INSTALL_AUTO: 1
      PS_ERASE_DB: 0
      DB_SERVER: mysql
      DB_USER: root
      DB_PASSWD: root
      DB_NAME: prestashop
      PS_DOMAIN: localhost:8080
    ports:
      - 8080:80

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
          PMA_HOST: mysql
      ports:
          - 8081:80
      depends_on:
          - mysql