<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerArz7e68\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerArz7e68/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerArz7e68.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerArz7e68\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerArz7e68\appDevDebugProjectContainer([
    'container.build_hash' => 'Arz7e68',
    'container.build_id' => '44c95151',
    'container.build_time' => 1671588763,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerArz7e68');
