<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6dxfjtz\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6dxfjtz/appProdProjectContainer.php') {
    touch(__DIR__.'/Container6dxfjtz.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container6dxfjtz\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container6dxfjtz\appProdProjectContainer([
    'container.build_hash' => '6dxfjtz',
    'container.build_id' => '8b30efca',
    'container.build_time' => 1671572919,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6dxfjtz');
