<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEbwsuck\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEbwsuck/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerEbwsuck.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerEbwsuck\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerEbwsuck\appProdProjectContainer([
    'container.build_hash' => 'Ebwsuck',
    'container.build_id' => 'a5dbc560',
    'container.build_time' => 1671571907,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEbwsuck');
