<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXhbdbtl\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXhbdbtl/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerXhbdbtl.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerXhbdbtl\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerXhbdbtl\appProdProjectContainer([
    'container.build_hash' => 'Xhbdbtl',
    'container.build_id' => '7d54a061',
    'container.build_time' => 1671589189,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXhbdbtl');
