name: Build and Push Docker Images

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build prod PrestaShop image
      run: |
        docker compose build prestashop
        
    - name: Build prod DataBase image
      run: |
        docker compose build mysql
        
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Push prod PrestaShop image
      run: |
        docker compose push docker.io/library/dresser-shop-prestashop
        
    - name: Push prod DataBase image
      run: |
        docker compose push docker.io/library/dresser-shop-mysql